import { type NextPage } from "next"
import { useRouter } from "next/router"
import Head from "next/head";
import { SellerItemCard } from "~/components/SellerItemCard";

const SellerProfile: NextPage = () => {
    const router = useRouter();
    const seller = api.sellers.get.useQuery(
      {
      sellerId: router.query.id as string,
      }, {
      enabled: !!router.query.id,
      }
    );
    return (
        <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-first bg-zinc-100">
            <SellerItemCard />
        </main>
      </>
      )}
export default SellerProfile;
