import { type NextPage } from "next"
import { useRouter } from "next/router"
import Head from "next/head";
import { ProductCard} from "~/components/ProductCard";

const SellerProfile: NextPage = () => {
    const router = useRouter();
    const { seller } = router.query

//    const seller = api.sellers.get.useQuery(
//      {
 //     sellerId: router.query.id as string,
//      }, {
///     enabled: !!router.query.id,
//      }
//    );
    return (
        <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-first bg-zinc-100">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4 p-4">
            <ProductCard />
          </div>
        </main>
      </>
      )}
export default SellerProfile;
