import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { ProfileCard } from "~/components/ProfileCard";

const ProfileView: NextPage = () => {
  const router = useRouter();

  const seller = api.sellers.get.useQuery(
    {
      memberId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );
  const sellerProfile = seller.data;

  if (!sellerProfile) {
    return null;
  }

  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen items-start justify-center bg-zinc-100 py-8">
        <div className="max-w-xl mx-auto p-4">
          <ProfileCard seller={sellerProfile} />
        </div>
      </main>
    </>
  );
};

export default ProfileView;
