/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { ProfileCard } from "~/components/ProfileCard";

const ProfileView: NextPage = () => {
  const router = useRouter();

  const seller = api.sellers.get.useQuery(
    {
      memberId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );

  const sellerItem = seller.data;

  if (!sellerItem) {
    return null;
  }

  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-first bg-zinc-100">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4 p-4">
            <ProfileCard />
          </div>
        </main>
    </>
  );
};
export default ProfileView;