import Head from "next/head";
import SimpleMap from "~/components/SimpleMap";
import { api } from "~/utils/api";
import { useUser, UserButton } from "@clerk/nextjs"

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-zinc-100">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-slate-800 sm:text-[5rem]">
            IndonesiansNC.com
            <SimpleMap />
          </h1>
          <p className="text-2xl text-slate-800">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
