import { useState } from "react";
import Head from "next/head";
import { api } from "~/utils/api";
import { MapListSelect } from "~/components/MapListSelect";
import ProductMapView from "~/components/ProductMapView";
import { ProductListView } from "~/components/ProductListView";

export default function Home() {
  const [view, setView] = useState<"map" | "list">("map");

  const handleViewChange = (selectedView: "map" | "list") => {
    setView(selectedView);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-full flex-col items-center justify-start bg-zinc-100">
        <div className="container flex flex-col items-center justify-start gap-12 px-4 py-8">
          <MapListSelect onViewChange={handleViewChange} />
          {view === "map" ? <ProductMapView /> : <ProductListView />}
        </div>
      </main>
    </>
  );
}