import Head from "next/head";
import { api } from "~/utils/api";
import { useUser} from "@clerk/nextjs"
import { ProfileUpdateStatus } from "~/components/ProfileUpdateStatus";

export default function Profile() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
  const user = useUser();
  const phoneNumber = user?.user?.hasVerifiedPhoneNumber ? user?.user?.primaryPhoneNumber?.phoneNumber : "No number found";
  const emailAddress = user.user?.hasVerifiedEmailAddress ? user.user?.primaryEmailAddress?.emailAddress : "No email address found";
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-first bg-zinc-100">
        <ProfileUpdateStatus />
        <div className="flex flex-col capitalize">
            <p>Hello {user.user?.firstName} !</p>
        </div>
        <div className="flex flex-cop items-start justify-start">
            <dl className="max-w-md text-gray-900 divide-y divide-gray-200 dark:text-white dark:divide-gray-700">
                <div className="flex flex-col pb-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Email address</dt>
                    <dd className="text-lg font-semibold">{emailAddress}</dd>
                </div>
                <div className="flex flex-col pt-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Phone number</dt>
                    <dd className="text-lg font-semibold">{phoneNumber}</dd>
                </div>
                <div className="flex flex-col py-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">County</dt>
                    <dd className="text-lg font-semibold">Rowan</dd>
                </div>
                <div className="flex flex-col pt-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Indonesian province</dt>
                    <dd className="text-lg font-semibold">Yogyakarta</dd>
                </div>
            </dl>
        </div>
      </main>
    </>
  );
}
