import Head from "next/head";
import { api } from "~/utils/api";
import { useUser} from "@clerk/nextjs"

export default function Profile() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
  const user = useUser();
  const phoneNumber = user?.user?.hasVerifiedPhoneNumber ? user?.user?.primaryPhoneNumber?.phoneNumber : "No number found";
  const emailAddress = user.user?.hasVerifiedEmailAddress ? user.user?.primaryEmailAddress?.emailAddress : "No email address found";
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-first bg-zinc-100">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 w-auto">      
            <ol className="flex items-center w-full text-sm font-medium text-center text-gray-500 dark:text-gray-400 sm:text-base">
                <li className="flex md:w-full items-center text-blue-600 dark:text-blue-500 sm:after:content-[''] after:w-full after:h-1 after:border-b after:border-gray-200 after:border-1 after:hidden sm:after:inline-block after:mx-6 xl:after:mx-10 dark:after:border-gray-700">
                    <span className="flex items-center after:content-['/'] sm:after:hidden after:mx-2 after:text-gray-200 dark:after:text-gray-500">
                        <svg aria-hidden="true" className="w-4 h-4 mr-2 sm:w-5 sm:h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                        Personal <span className="hidden sm:inline-flex sm:ml-2">Info</span>
                    </span>
                </li>
                <li className="flex md:w-full items-center after:content-[''] after:w-full after:h-1 after:border-b after:border-gray-200 after:border-1 after:hidden sm:after:inline-block after:mx-6 xl:after:mx-10 dark:after:border-gray-700">
                    <span className="flex items-center after:content-['/'] sm:after:hidden after:mx-2 after:text-gray-200 dark:after:text-gray-500">
                        <span className="mr-2">2</span>
                        Seller <span className="hidden sm:inline-flex sm:ml-2">Info</span>
                    </span>
                </li>
                <li className="flex items-center">
                    <span className="mr-2">3</span>
                    Confirmation
                </li>
            </ol>
        </div>
        <div className="flex flex-col capitalize">
            <p>Hello {user.user?.firstName} !</p>
        </div>
        <div className="flex flex-cop items-start justify-start">
            <dl className="max-w-md text-gray-900 divide-y divide-gray-200 dark:text-white dark:divide-gray-700">
                <div className="flex flex-col pb-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Email address</dt>
                    <dd className="text-lg font-semibold">{emailAddress}</dd>
                </div>
                <div className="flex flex-col pt-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Phone number</dt>
                    <dd className="text-lg font-semibold">{phoneNumber}</dd>
                </div>
                <div className="flex flex-col py-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">County</dt>
                    <dd className="text-lg font-semibold">Rowan</dd>
                </div>
                <div className="flex flex-col pt-3">
                    <dt className="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Indonesian province</dt>
                    <dd className="text-lg font-semibold">Yogyakarta</dd>
                </div>
            </dl>
        </div>
      </main>
    </>
  );
}
