import Head from "next/head";
import { Card } from "~/components/Card";
import { api } from "~/utils/api";
import { SellerProfileCard } from "~/components/SellerProfileCard";
export default function Sellers() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-zinc-100">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <SellerProfileCard />
        </div>
      </main>
    </>
  );
}
