import Head from "next/head";
import { Card } from "~/components/Card";
import { api } from "~/utils/api";
import { SellerCard } from "~/components/SellerCard";
export default function Sellers() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-zinc-100">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4 p-4">
            <SellerCard />
        </div>
      </main>
    </>
  );
}
