/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { ProductCard } from "~/components/ProductCard";
import { Spinner } from "~/components/Spinner";

const StoresView: NextPage = () => {
  const router = useRouter();

  const productsQuery = api.products.get.useQuery(
    {
      memberId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );
  const sellerProducts = productsQuery.data;

  if (!sellerProducts) {
    return (
      <div className="flex items-center justify-center">
        No products found.
      </div>
    )
  }

  if (productsQuery.isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Spinner />
      </div>
      )
  }

  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-first bg-zinc-100">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4 p-4">
          {sellerProducts.map((product) => (
            <ProductCard key={product.id} product={product} />
          ))}
        </div>
      </main>
    </>
  );
};

export default StoresView;